### ISSUE TITLE
Error while running the codes

### ISSUE THREAD

**Issue by Roniyar16** [sheadan/NFMD-ExtractionInstantaneous#1]
I tried to run these codes on jupitor notebook and spyder... Bt facing some tensor error..

**Comment by sheadan** [comment]
I can probably help 😀 can you post the error you're receiving and/or example code reproducing the error?

**Comment by Roniyar16** [comment]
![IMG_20220111_101138](https://user-images.githubusercontent.com/97491805/148888911-fb7d3bd2-2230-4312-9ff8-b943ceb2ad04.jpg)

**Comment by Roniyar16** [comment]
Initially nfmd library was not importing then we solved this problem so the last problem we are going through is the "tensor object has no tensor attribute" While ruuning decompose signal function of class nfmd.

**Comment by Roniyar16** [comment]
Sir i have posted the issue and pic of error on the site

**Comment by sheadan** [comment]
Thank you this is very helpful! What version of Python and pytorch are you running?

**Comment by Roniyar16** [comment]
I am running it on spyder 5.15 which has python 3.9. 7 version. .. I also tried it on jupitor notebook... Can u please share me the nfmd library

**Comment by sheadan** [comment]
Can you run the following code and tell me what it outputs?
```
import torch
print(torch.__version__)
```

**Comment by Roniyar16** [comment]
![Uploading 16420059239906609157510859344239.jpg…]()

**Comment by Roniyar16** [comment]
Ok sir

**Comment by Roniyar16** [comment]
Ok sir

**Comment by Roniyar16** [comment]
I got ... Module 'torch' has no attribute '_version_

**Comment by Roniyar16** [comment]
I got ... Module 'torch' has no attribute '_version_

**Comment by sheadan** [comment]
Did you include the underscores before and after? it's critical to have two underscores before and two underscores after the word 'version' as in the example I posted.

**Comment by Roniyar16** [comment]
Ohh ok

**Comment by Roniyar16** [comment]
1.10.1+cpu

**Comment by Roniyar16** [comment]
Sir, is the version compatible??

**Comment by sheadan** [comment]
The version of Pytorch this code was developed with is `1.6.0'. If it's possible, can you try installing Pytorch 1.6? 

If this is still causing issues, I'll need to create a test environment like yours to figure out what's happening. Are you using Anaconda?

**Comment by Roniyar16** [comment]
Yes sir.. I m using anaconda

**Comment by Roniyar16** [comment]
I tried running the same code on jupitor notebook.. There also same issue

**Comment by Roniyar16** [comment]
Sir as Pytorch 1.6.0 is not compatible with python 3.9..so i am down grading the python version to python 3.7

**Comment by Roniyar16** [comment]
Sir, Which version of python should i install.. Cause Pytorch 1.6.0 is not compatible with  python 3.9

**Comment by sheadan** [comment]
My working example is using Python 3.8.5 and Pytorch 1.6.0. Does that combination work for you?

**Comment by Roniyar16** [comment]
I ll download that version now and let u know asap

**Comment by Roniyar16** [comment]
Sir,Are u using it on anaconda ???..

**Comment by sheadan** [comment]
Yes, my test environment is Anaconda on Windows 10

**Comment by Roniyar16** [comment]
Ok sir..

**Comment by Roniyar16** [comment]
Sir i am still facing issues. Is it possible if u could send me the code files through gmail.. Which is running on ur system??

**Comment by sheadan** [comment]
I can't recreate your error. The code in the repository works for me as-is without edits. I even tested this on a brand new Anaconda environment initialized in the following way using Python 3.6 and Pytorch 1.6. I configured the environment in the Anaconda Powershell prompt on Windows:

```
conda create -n nfmd-test python=3.6
conda activate nfmd-test
conda install pytorch=1.6 torchvision torchaudio cpuonly -c pytorch
conda install ipykernel pandas matplotlib
pip install pyhht
python -m ipykernel install --user --name=nfmd_test --display-name="nfmd-test"
```

Then I can start Jupyter notebook by running the following command, still in Anaconda Powershell.
```
jupyter-notebook
```

If I go to the Figure 4 notebook in Jupyter notebook ("Fig 4 - Clean Signal NFMD vs HHT.ipynb") and ensure that the kernel is set to use "nfmd-test" by selecting the Kernel menu -> Change kernel -> selecting the "nfmd-test" kernel. I can then run Figure 4 notebook without any errors at all. The only change I make is commenting out the last two lines in the first notebook box:

```
#full_params, half_params = get_plot_params()
#plt.rcParams.update(full_params)
```

and the first line in the final box:

`#plt.rcParams.update(full_params)`

to simplify the plotting procedure.

I have also tested this on Pytorch 1.10 and the only change you need is on line 120 of NFMD.py, where you change

`self.losses.append(loss)`

to

`self.losses.append(loss.detach())`

If neither of the above steps fix your issue, can you post your .py script that is causing the error?

**Comment by Roniyar16** [comment]
_sir, i followed the above steps u mentioned....if i comment out the last two lines in the first notebook box: then
the error occurs in last notebook box as follows:_


---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\texmanager.py in _run_checked_subprocess(self, command, tex)
    276                                              cwd=self.texcache,
--> 277                                              stderr=subprocess.STDOUT)
    278         except FileNotFoundError as exc:

~\anaconda3\envs\nfmd-test\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    355     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 356                **kwargs).stdout
    357 

~\anaconda3\envs\nfmd-test\lib\subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    422 
--> 423     with Popen(*popenargs, **kwargs) as process:
    424         try:

~\anaconda3\envs\nfmd-test\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:

~\anaconda3\envs\nfmd-test\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1016                                          os.fspath(cwd) if cwd is not None else None,
-> 1017                                          startupinfo)
   1018             finally:

FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-20-d902ef450810> in <module>
     95 #plt.subplots_adjust(left=None, bottom=None, right=None, top=None, wspace=0.1, hspace=0.1)
     96 
---> 97 plt.savefig("shea4.png")
     98 
     99 plt.show()

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\pyplot.py in savefig(*args, **kwargs)
    857 def savefig(*args, **kwargs):
    858     fig = gcf()
--> 859     res = fig.savefig(*args, **kwargs)
    860     fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
    861     return res

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\figure.py in savefig(self, fname, transparent, **kwargs)
   2309                 patch.set_edgecolor('none')
   2310 
-> 2311         self.canvas.print_figure(fname, **kwargs)
   2312 
   2313         if transparent:

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2191                            else suppress())
   2192                     with ctx:
-> 2193                         self.figure.draw(renderer)
   2194 
   2195                     bbox_inches = self.figure.get_tightbbox(

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1852             renderer.open_group('figure', gid=self.get_gid())
   1853             if self.get_constrained_layout() and self.axes:
-> 1854                 self.execute_constrained_layout(renderer)
   1855             if self.get_tight_layout() and self.axes:
   1856                 try:

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\figure.py in execute_constrained_layout(self, renderer)
   2564         if renderer is None:
   2565             renderer = layoutbox.get_renderer(fig)
-> 2566         do_constrained_layout(fig, renderer, h_pad, w_pad, hspace, wspace)
   2567 
   2568     @cbook._delete_parameter("3.2", "renderer")

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\_constrained_layout.py in do_constrained_layout(fig, renderer, h_pad, w_pad, hspace, wspace)
    158                 # make margins for each layout box based on the size of
    159                 # the decorators.
--> 160                 _make_layout_margins(ax, renderer, h_pad, w_pad)
    161 
    162         # do layout for suptitle.

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\_constrained_layout.py in _make_layout_margins(ax, renderer, h_pad, w_pad)
    260     pos = ax.get_position(original=True)
    261     try:
--> 262         tightbbox = ax.get_tightbbox(renderer=renderer, for_layout_only=True)
    263     except TypeError:
    264         tightbbox = ax.get_tightbbox(renderer=renderer)

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axes\_base.py in get_tightbbox(self, renderer, call_axes_locator, bbox_extra_artists, for_layout_only)
   4161                 try:
   4162                     bb_yaxis = self.yaxis.get_tightbbox(
-> 4163                         renderer, for_layout_only=for_layout_only)
   4164                 except TypeError:
   4165                     # in case downstream library has redefined axis:

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in get_tightbbox(self, renderer, for_layout_only)
   1109         ticks_to_draw = self._update_ticks()
   1110 
-> 1111         self._update_label_position(renderer)
   1112 
   1113         # go back to just this axis's tick labels

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in _update_label_position(self, renderer)
   2351         # get bounding boxes for this axis and any siblings
   2352         # that have been set by `fig.align_ylabels()`
-> 2353         bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)
   2354 
   2355         x, y = self.label.get_position()

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in _get_tick_boxes_siblings(self, renderer)
   2336         for axx in grp.get_siblings(self.axes):
   2337             ticks_to_draw = axx.yaxis._update_ticks()
-> 2338             tlb, tlb2 = axx.yaxis._get_tick_bboxes(ticks_to_draw, renderer)
   2339             bboxes.extend(tlb)
   2340             bboxes2.extend(tlb2)

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in _get_tick_bboxes(self, ticks, renderer)
   1090         """Return lists of bboxes for ticks' label1's and label2's."""
   1091         return ([tick.label1.get_window_extent(renderer)
-> 1092                  for tick in ticks if tick.label1.get_visible()],
   1093                 [tick.label2.get_window_extent(renderer)
   1094                  for tick in ticks if tick.label2.get_visible()])

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in <listcomp>(.0)
   1090         """Return lists of bboxes for ticks' label1's and label2's."""
   1091         return ([tick.label1.get_window_extent(renderer)
-> 1092                  for tick in ticks if tick.label1.get_visible()],
   1093                 [tick.label2.get_window_extent(renderer)
   1094                  for tick in ticks if tick.label2.get_visible()])

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\text.py in get_window_extent(self, renderer, dpi)
    900 
    901         with cbook._setattr_cm(self.figure, dpi=dpi):
--> 902             bbox, info, descent = self._get_layout(self._renderer)
    903             x, y = self.get_unitless_position()
    904             x, y = self.get_transform().transform((x, y))

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\text.py in _get_layout(self, renderer)
    287         _, lp_h, lp_d = renderer.get_text_width_height_descent(
    288             "lp", self._fontproperties,
--> 289             ismath="TeX" if self.get_usetex() else False)
    290         min_dy = (lp_h - lp_d) * self._linespacing
    291 

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\backends\backend_agg.py in get_text_width_height_descent(self, s, prop, ismath)
    226             fontsize = prop.get_size_in_points()
    227             w, h, d = texmanager.get_text_width_height_descent(
--> 228                 s, fontsize, renderer=self)
    229             return w, h, d
    230 

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\texmanager.py in get_text_width_height_descent(self, tex, fontsize, renderer)
    421         else:
    422             # use dviread.
--> 423             dvifile = self.make_dvi(tex, fontsize)
    424             with dviread.Dvi(dvifile, 72 * dpi_fraction) as dvi:
    425                 page, = dvi

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\texmanager.py in make_dvi(self, tex, fontsize)
    309                 self._run_checked_subprocess(
    310                     ["latex", "-interaction=nonstopmode", "--halt-on-error",
--> 311                      texfile], tex)
    312             for fname in glob.glob(basefile + '*'):
    313                 if not fname.endswith(('dvi', 'tex')):

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\texmanager.py in _run_checked_subprocess(self, command, tex)
    279             raise RuntimeError(
    280                 'Failed to process string with tex because {} could not be '
--> 281                 'found'.format(command[0])) from exc
    282         except subprocess.CalledProcessError as exc:
    283             raise RuntimeError(

RuntimeError: Failed to process string with tex because latex could not be found

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\texmanager.py in _run_checked_subprocess(self, command, tex)
    276                                              cwd=self.texcache,
--> 277                                              stderr=subprocess.STDOUT)
    278         except FileNotFoundError as exc:

~\anaconda3\envs\nfmd-test\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    355     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 356                **kwargs).stdout
    357 

~\anaconda3\envs\nfmd-test\lib\subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    422 
--> 423     with Popen(*popenargs, **kwargs) as process:
    424         try:

~\anaconda3\envs\nfmd-test\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:

~\anaconda3\envs\nfmd-test\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1016                                          os.fspath(cwd) if cwd is not None else None,
-> 1017                                          startupinfo)
   1018             finally:

FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
~\anaconda3\envs\nfmd-test\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~\anaconda3\envs\nfmd-test\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~\anaconda3\envs\nfmd-test\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2191                            else suppress())
   2192                     with ctx:
-> 2193                         self.figure.draw(renderer)
   2194 
   2195                     bbox_inches = self.figure.get_tightbbox(

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1852             renderer.open_group('figure', gid=self.get_gid())
   1853             if self.get_constrained_layout() and self.axes:
-> 1854                 self.execute_constrained_layout(renderer)
   1855             if self.get_tight_layout() and self.axes:
   1856                 try:

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\figure.py in execute_constrained_layout(self, renderer)
   2564         if renderer is None:
   2565             renderer = layoutbox.get_renderer(fig)
-> 2566         do_constrained_layout(fig, renderer, h_pad, w_pad, hspace, wspace)
   2567 
   2568     @cbook._delete_parameter("3.2", "renderer")

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\_constrained_layout.py in do_constrained_layout(fig, renderer, h_pad, w_pad, hspace, wspace)
    158                 # make margins for each layout box based on the size of
    159                 # the decorators.
--> 160                 _make_layout_margins(ax, renderer, h_pad, w_pad)
    161 
    162         # do layout for suptitle.

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\_constrained_layout.py in _make_layout_margins(ax, renderer, h_pad, w_pad)
    260     pos = ax.get_position(original=True)
    261     try:
--> 262         tightbbox = ax.get_tightbbox(renderer=renderer, for_layout_only=True)
    263     except TypeError:
    264         tightbbox = ax.get_tightbbox(renderer=renderer)

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axes\_base.py in get_tightbbox(self, renderer, call_axes_locator, bbox_extra_artists, for_layout_only)
   4161                 try:
   4162                     bb_yaxis = self.yaxis.get_tightbbox(
-> 4163                         renderer, for_layout_only=for_layout_only)
   4164                 except TypeError:
   4165                     # in case downstream library has redefined axis:

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in get_tightbbox(self, renderer, for_layout_only)
   1109         ticks_to_draw = self._update_ticks()
   1110 
-> 1111         self._update_label_position(renderer)
   1112 
   1113         # go back to just this axis's tick labels

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in _update_label_position(self, renderer)
   2351         # get bounding boxes for this axis and any siblings
   2352         # that have been set by `fig.align_ylabels()`
-> 2353         bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)
   2354 
   2355         x, y = self.label.get_position()

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in _get_tick_boxes_siblings(self, renderer)
   2336         for axx in grp.get_siblings(self.axes):
   2337             ticks_to_draw = axx.yaxis._update_ticks()
-> 2338             tlb, tlb2 = axx.yaxis._get_tick_bboxes(ticks_to_draw, renderer)
   2339             bboxes.extend(tlb)
   2340             bboxes2.extend(tlb2)

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in _get_tick_bboxes(self, ticks, renderer)
   1090         """Return lists of bboxes for ticks' label1's and label2's."""
   1091         return ([tick.label1.get_window_extent(renderer)
-> 1092                  for tick in ticks if tick.label1.get_visible()],
   1093                 [tick.label2.get_window_extent(renderer)
   1094                  for tick in ticks if tick.label2.get_visible()])

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\axis.py in <listcomp>(.0)
   1090         """Return lists of bboxes for ticks' label1's and label2's."""
   1091         return ([tick.label1.get_window_extent(renderer)
-> 1092                  for tick in ticks if tick.label1.get_visible()],
   1093                 [tick.label2.get_window_extent(renderer)
   1094                  for tick in ticks if tick.label2.get_visible()])

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\text.py in get_window_extent(self, renderer, dpi)
    900 
    901         with cbook._setattr_cm(self.figure, dpi=dpi):
--> 902             bbox, info, descent = self._get_layout(self._renderer)
    903             x, y = self.get_unitless_position()
    904             x, y = self.get_transform().transform((x, y))

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\text.py in _get_layout(self, renderer)
    287         _, lp_h, lp_d = renderer.get_text_width_height_descent(
    288             "lp", self._fontproperties,
--> 289             ismath="TeX" if self.get_usetex() else False)
    290         min_dy = (lp_h - lp_d) * self._linespacing
    291 

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\backends\backend_agg.py in get_text_width_height_descent(self, s, prop, ismath)
    226             fontsize = prop.get_size_in_points()
    227             w, h, d = texmanager.get_text_width_height_descent(
--> 228                 s, fontsize, renderer=self)
    229             return w, h, d
    230 

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\texmanager.py in get_text_width_height_descent(self, tex, fontsize, renderer)
    421         else:
    422             # use dviread.
--> 423             dvifile = self.make_dvi(tex, fontsize)
    424             with dviread.Dvi(dvifile, 72 * dpi_fraction) as dvi:
    425                 page, = dvi

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\texmanager.py in make_dvi(self, tex, fontsize)
    309                 self._run_checked_subprocess(
    310                     ["latex", "-interaction=nonstopmode", "--halt-on-error",
--> 311                      texfile], tex)
    312             for fname in glob.glob(basefile + '*'):
    313                 if not fname.endswith(('dvi', 'tex')):

~\anaconda3\envs\nfmd-test\lib\site-packages\matplotlib\texmanager.py in _run_checked_subprocess(self, command, tex)
    279             raise RuntimeError(
    280                 'Failed to process string with tex because {} could not be '
--> 281                 'found'.format(command[0])) from exc
    282         except subprocess.CalledProcessError as exc:
    283             raise RuntimeError(

RuntimeError: Failed to process string with tex because latex could not be found

<Figure size 2190x1095 with 6 Axes>

**Comment by sheadan** [comment]
Hello,

This error ("RuntimeError: Failed to process string with tex because latex could not be found") is because Matplotlib is trying to use LaTeX for rendering the text in the plots. One of the lines of codes I mentioned commenting out must have been run to make Matplotlib attempt using LaTeX; perhaps based on your comments you did not comment out the first line in the last box, listed below?
```
plt.rcParams.update(full_params)
```

An easy way to solve this is finding the command: 
```
fig3 = plt.figure(constrained_layout=True)
```

and adding the following two lines **before** the above command:
```
import matplotlib as mpl
plt.rcParams.update(mpl.rcParamsDefault)
```

Does that work?

**Comment by Roniyar16** [comment]
sir ,I commented out last two lines of first box..and first line of last box... still same error

**Comment by Roniyar16** [comment]
yes sir,,,,this worked 
**adding the following two lines before the above command:

import matplotlib as mpl
plt.rcParams.update(mpl.rcParamsDefault)**
i ll check all the 12 examples and let u know if any issues i face...

**Comment by sheadan** [comment]
Excellent! This is great progress.   Does the script that originally caused you issues work now? Also please do let me know how the other example notebooks run.

I will update the example notebooks to disable the use of LaTeX for rendering text on Matplotlib tomorrow, as I imagine this could cause issues for others as well.

**Comment by Roniyar16** [comment]
sir,,all the examples are running using these codes :
  import matplotlib as mpl
plt.rcParams.update(mpl.rcParamsDefault)...
 thanks for helping me with the issue...

**Comment by sheadan** [comment]
Thanks for working through this with me. I'll make some changes based on our conversation around the plotting functions to remove LaTeX as default text renderer. Let me know if you have any other issues.

**Comment by Roniyar16** [comment]
sir, i had a complex signal generated in matlab, i want to test that signal on the example codes, how can i do the same?
